### ISSUE TITLE
issue loading files

### ISSUE THREAD

**Issue by mgazzin** [fastschema/fastschema#32]
Hello, very nice project! Well done! 
I have a problem uploading a PDF file. I am getting:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13d3ab7]

goroutine 223 [running]:
github.com/fastschema/fastschema/services/media.(*MediaService).Upload.func1(0xc0001901e0, 0xc0000fda00?)
	github.com/fastschema/fastschema/services/media/upload.go:30 +0xd7
created by github.com/fastschema/fastschema/services/media.(*MediaService).Upload in goroutine 98
	github.com/fastschema/fastschema/services/media/upload.go:27 +0x112
```

 I have also put the following in my .env file:

```
STORAGE_DEFAULT_DISK=local
STORAGE_DISKS=[{"name":"local","driver":"local","root":"/public/files","base_url":"http://localhost:8000/files"},{"name":"my_s3","driver":"s3","root":"/files","provider":"DigitalOcean","endpoint":"sfo3.digitaloceanspaces.com","region":"sfo3","bucket":"my_bucket","access_key_id":"s3_access_key_id","secret_access_key":"s3_secret_access_key","base_url":"https://cdn.site.local"}]
```

without any result.
I have also tried to run the docker container with the following command:

```
docker run -d -p 8000:8000 -v ./fastschema/data:/fastschema/data   -v ./files:/public/files ghcr.io/fastschema/fastschema:latest
```

without any result.
Could you please tell me what is the correct setting?
Thanks @ngocphuongnb

**Comment by ngocphuongnb** [comment]
@mgazzin Thank you for reporting the error.
I have tested and confirmed that an error occurs when there is no environment information for storage.
I set the `STORAGE_DEFAULT_DISK` and `STORAGE_DISKS` environment variables to the `data/.env` file and the error went away.
Can you check to see if the `.env` file has been placed in the data folder, or is it in the root folder?
Fastschema will load the env file in `data/.env` instead of the root directory.
I will also update Fastschema to set default local disk when there is no environment variable to avoid this error in the future.

**Comment by mgazzin** [comment]
ok @ngocphuongnb , now it is working.
Is preview available for PDF files? I can't see it.

**Comment by ngocphuongnb** [comment]
@mgazzin The pdf preview feature is currently unavailable. There are more priority tasks so I will update the file feature later.

**Comment by mgazzin** [comment]
Ok I agree.
It would be interesting to have a list of features you want to implement. I am just curious, take your time of course @ngocphuongnb .
Thanks anyway for this project @ngocphuongnb . It looks very interesting.

**Comment by ngocphuongnb** [comment]
@mgazzin Thank you, I am going to close this issue, please create a new one if you have any problems with Fastschema.
