### ISSUE TITLE
I can't display an added field

### ISSUE THREAD

**Issue by mgazzin** [fastschema/fastschema#70]
Hello, this project looks very good and interesting.
I am making some tests and I defined a Category table and then I added a new filed 'Content':

![immagine](https://github.com/fastschema/fastschema/assets/7835130/07fc6897-fb2d-45ad-9316-809c0f100cf9)

If I go to the content I can't see this new field:

![immagine](https://github.com/fastschema/fastschema/assets/7835130/8596b6d4-9294-45bc-9e28-8b5433f0ec5e)

Any reason?

**Comment by ngocphuongnb** [comment]
Thanks for submitting the issue!
The content list table will display both field name and field content, so to prevent the table from overflowing due to long text, FastSchema will ignore this type of field from the list content page.
Basically, other fields such as enums or relations will not be displayed here. I will implement it in the near future.
