### ISSUE TITLE
extension for PDF preview

### ISSUE THREAD

**Issue by mgazzin** [fastschema/fastschema#71]
Hello, what is the rationale for an extension of fastschema that allows me to have a PDF preview ?

![immagine](https://github.com/fastschema/fastschema/assets/7835130/2ed372b9-da61-4b2b-b26e-5d32a4187173)

Could you please explain to me?

**Comment by ngocphuongnb** [comment]
FastSchema intends to support previewing some basic file types. However, I don't have enough time right now so I can only build an image preview function.
Thank you for your interest!

**Comment by mgazzin** [comment]
Thanks @ngocphuongnb 
Any suggestion if I want to build on my own?

**Comment by ngocphuongnb** [comment]
@mgazzin to build a pdf previewer, we will need to update the [media previewe component](https://github.com/fastschema/dash/blob/8e61360683e24acee9eb3d50e0fc92d0e5878e26/src/components/media/preview.tsx).
I would try [react-pdf](https://github.com/wojtekmaj/react-pdf) for this function because it is a great library and work well with nextjs.
